modLoader = "javafml"
loaderVersion = "[37,)"
license = "MIT"
issueTrackerURL = "https://github.com/RaphiMC/OpenAuthMod/issues"

[[mods]]
modId = "openauthmod"
version = "${version}"
displayName = "Open Auth Mod"
displayURL = "https://github.com/RaphiMC/OpenAuthMod"
logoFile = "logo.png"
authors = "RK_01, Lenni0451"
description = "Authenticate with proxies during login or play state to allow online mode server switching."

[[dependencies.openauthmod]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openauthmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.18.2]"
ordering = "NONE"
side = "CLIENT"
