modLoader = "javafml"
loaderVersion = "[10,)"
license = "MIT"
issueTrackerURL = "https://github.com/RaphiMC/OpenAuthMod/issues"
[[mods]]
modId = "oam"
version = "${version}"
displayName = "Open Auth Mod"
displayURL = "https://github.com/RaphiMC/OpenAuthMod"
#logoFile = "assets/oam/logo.png" #Forge requires the logo to be in the root. The game crashes if it's not.
authors = "RK_01, Lenni0451"
description = "Authenticate with proxies during login or play state to allow online mode server switching."