modLoader = "javafml"
loaderVersion = "[24,)"
license = "MIT"
issueTrackerURL = "https://github.com/RaphiMC/OpenAuthMod/issues"

[[mods]]
modId = "oam"
version = "${version}"
displayName = "Open Auth Mod"
displayURL = "https://github.com/RaphiMC/OpenAuthMod"
logoFile = "logo.png"
authors = "RK_01, Lenni0451"
description = "Authenticate with proxies during login or play state to allow online mode server switching."

[[dependencies.oam]]
modId = "forge"
mandatory = true
versionRange = "[24,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.oam]]
modId = "minecraft"
mandatory = true
versionRange = "[1.14,1.16.5]"
ordering = "NONE"
side = "CLIENT"
